import styles from "./Snapshot.module.css";

const HIGHLIGHTS = [
  {
    description:
      "Voice + text assessment delivered as a one-on-one dialogue — not a quiz, not a form.",
    icon: "🎙",
    title: "Conversational AI",
  },
  {
    description:
      "Questions autogenerated from your board's chapters, tagged by Bloom's Taxonomy level.",
    icon: "📋",
    title: "NCERT Question Engine",
  },
  {
    description:
      "Per-student reports on conceptual depth, communication, and identified gaps — HPC-aligned.",
    icon: "📊",
    title: "Insight Reports",
  },
];

export default function Snapshot() {
  return (
    <section className="section" id="product">
      <div className="container">
        <div className="section-head">
          <p className="label label--accent">What Proctors Is</p>
          <h2>
            A curriculum-native AI assessment platform — built for Indian
            schools, scaled for classrooms of 40.
          </h2>
          <p>
            Most assessment platforms measure whether a student got an answer
            right. Proctors measures whether a student understood why.
          </p>
          <p className={styles.secondPara}>
            The platform sits directly on top of the curriculum your school
            already teaches. After a chapter is covered in class, a teacher
            assigns a Proctor assessment. Every student — not just the fast
            ones, not just the ones who raise their hand — gets a private,
            voice-based AI dialogue built around that exact chapter. Proctor
            asks, listens, follows up, and produces a per-student insight report
            the teacher receives the same week.
          </p>
        </div>
        <div className={styles.row}>
          {HIGHLIGHTS.map((h, i) => (
            <div
              className={`glass-panel reveal ${styles.card}`}
              key={h.title}
              style={{ transitionDelay: `${i * 100}ms` }}
            >
              <span aria-hidden="true" className={styles.icon}>
                {h.icon}
              </span>
              <h3 className={styles.title}>{h.title}</h3>
              <p className={styles.desc}>{h.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
